**# PANDAS**

Pandas is a python library used for working with data sets .

It has functions for analyzing , cleaning, exploring and maniplulating data .

Pandas allows us to analyze big and make conclusions based on statistical theories  .

Pandas can clean messy data sets , and make more readable and relevant .

Relevant data is very important in data science .

In pandas 1dimension is called series . 2 dimension is called data frame . 3 dimension is called pannel .

SERIES GENERATION

In [ ]:
import pandas as pd
data = [2,4,6,8,9]
s = pd.Series(data)
print(s)

0    2
1    4
2    6
3    8
4    9
dtype: int64

In [ ]:
#array in series
import pandas as pd
import numpy as np

data = np.array([2,4,6,8,9,10])
s = pd.Series(data)
print(s)

0     2
1     4
2     6
3     8
4     9
5    10
dtype: int64

In [ ]:
import pandas as pd
data = [2,4,6,8,9,188,365]
s = pd.Series(data)
print(s)

0      2
1      4
2      6
3      8
4      9
5    188
6    365
dtype: int64

In [ ]:
#LIST

import pandas as pd

import numpy as np

data1 = [1,3,5,7,9]

print(type(data1),'\n')

s = pd.Series(data1)

print(s)

<class 'list'>

0    1
1    3
2    5
3    7
4    9
dtype: int64

In [ ]:
#TUPLE

import pandas as pd

data2 = (10, 20, 30, 40, 50)

print(type(data2),'\n')

series = pd.Series(data2)

print(series)

<class 'tuple'>

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
import pandas as pd

data = (4,5,6,7)

s = pd.Series(data)

print(s,'\n')

print('Shape : ',s.shape)

print('Dimension : ',s.ndim)

print('D',s.dtype)

0    4
1    5
2    6
3    7
dtype: int64

Shape :  (4,)
Dimension :  1
D int64

In [ ]:
import pandas as pd
data = (2,4,5,6)
s = pd.Series(data)
print(s)
print(s.shape)
print(s.ndim)
print(s.dtype)

0    2
1    4
2    5
3    6
dtype: int64
(4,)
1
int64

Custom Indexing

In [ ]:
#INDEXING

import pandas as pd

import numpy as np

data = ([4,5,6,7])

s = pd.Series(data,index = [100,101,102,103])

print(s)

100    4
101    5
102    6
103    7
dtype: int64

In [ ]:
#DICTIONARY

import pandas as pd

data = {1:'shaluu',2:'nasrn',3:'fathm'}

s = pd.Series(data)

print(s)

1    shaluu
2     nasrn
3     fathm
dtype: object

In [ ]:
#INDEXING


import pandas as pd

import numpy as np

data = {1:'shahla',2:'fathm',3:'nsrn'}

s = pd.Series(data,index = [5,1,8,2,3,4])

print(s)

5       NaN
1    shahla
8       NaN
2     fathm
3      nsrn
4       NaN
dtype: object

In [ ]:
#INDEXING A PARTICULAR VALUE

import pandas as pd

import numpy as np

data = {1:'shahla',2:'fathm',3:'nsrn'}

s = pd.Series(data,index = [5,1,8,2,3,4])

print(s[3])

nsrn

In [ ]:
#INDEXING MULTIPLE VALUES

import pandas as pd

import numpy as np

data = {1:'shahla',2:'fathm',3:'nsrn'}

s = pd.Series(data,index = [5,1,8,2,3,4])

print(s[[3,5]])

3    nsrn
5     NaN
dtype: object

In [ ]:
#SLICING

import pandas as pd

import numpy as np

data = {1:'shahla',2:'fathm',3:'nsrn'}

s = pd.Series(data,index = [5,1,8,2,3,4])

print(s[0:3])

5       NaN
1    shahla
8       NaN
dtype: object

#Data frame

In [ ]:
import pandas as pd
import numpy as np

data = [[2,4,6,8],[1,2,3,4]]
s = pd.DataFrame(data)
print(s)

   0  1  2  3
0  2  4  6  8
1  1  2  3  4

In [ ]:
import pandas as pd
import numpy as np

data = [['fathima',2,4,6,8],['nasrin',1,2,3,4]]
s = pd.DataFrame(data)
print(s)

         0  1  2  3  4
0  fathima  2  4  6  8
1   nasrin  1  2  3  4

In [ ]:
import pandas as pd
import numpy as np

data1 = {'Name':['fathima','nasrin','ke'],'english':[40,60,40],'maths':[40,60,40],'chem':[40,60,40]}
df = pd.DataFrame(data1)
print(df)

      Name  english  maths  chem
0  fathima       40     40    40
1   nasrin       60     60    60
2       ke       40     40    40

In [ ]:
import pandas as pd
import numpy as np

data1 = {'Name':['fathima','nasrin','ke'],'english':[40,60,40],'maths':[40,60,40],'chem':[40,60,40]}
df = pd.DataFrame(data1)

df['social'] = [60,48,50]
df['total marks'] = df['english'] + df['maths'] + df['chem'] + df['social']
print(df)

      Name  english  maths  chem  social  total marks
0  fathima       40     40    40      60          180
1   nasrin       60     60    60      48          228
2       ke       40     40    40      50          170

In [ ]:
import pandas as pd
import numpy as np

data1 = {'Name':['fathima','nasrin','ke'],'english':[40,60,40],'maths':[40,60,40],'chem':[40,60,40]}
df = pd.DataFrame(data1)

df['social'] = [60,48,50]
df['total marks'] = df['english'] + df['maths'] + df['chem'] + df['social']

list1 = []

for i in df['total marks']:

  if i<=100:
     list1.append('below avrg')
  elif i<=200:
    list1.append('avg')
  else :
    list1.append('excellent')

df['status'] = list1
print(df)

      Name  english  maths  chem  social  total marks     status
0  fathima       40     40    40      60          180        avg
1   nasrin       60     60    60      48          228  excellent
2       ke       40     40    40      50          170        avg

In [ ]:
import pandas as pd
import numpy as np

data1 = {'Name':['fathima','nasrin','ke'],'english':[40,60,40],'maths':[40,60,40],'chem':[40,60,40]}
df = pd.DataFrame(data1)

df['social'] = [60,48,50]
df['total marks'] = df['english'] + df['maths'] + df['chem'] + df['social']

list1 = []

for i in df['total marks']:

  if i<=100:
     list1.append('below avrg')
  elif i<=200:
    list1.append('avg')
  else :
    list1.append('excellent')

df['status'] = list1
print(df)
print(df[['Name','status','chem']])

      Name  english  maths  chem  social  total marks     status
0  fathima       40     40    40      60          180        avg
1   nasrin       60     60    60      48          228  excellent
2       ke       40     40    40      50          170        avg
      Name     status  chem
0  fathima        avg    40
1   nasrin  excellent    60
2       ke        avg    40

DELETING

In [ ]:
import pandas as pd
import numpy as np

data1 = {'Name':['fathima','nasrin','ke'],'english':[40,60,40],'maths':[40,60,40],'chem':[40,60,40]}
df = pd.DataFrame(data1)

df['social'] = [60,48,50]
df['total marks'] = df['english'] + df['maths'] + df['chem'] + df['social']

list1 = []

for i in df['total marks']:

  if i<=100:
     list1.append('below avrg')
  elif i<=200:
    list1.append('avg')
  else :
    list1.append('excellent')

df['status'] = list1
del df['maths']
df = df.drop('chem',axis = 1) # want to specify axis
print(df)

      Name  english  social  total marks     status
0  fathima       40      60          180        avg
1   nasrin       60      48          228  excellent
2       ke       40      50          170        avg

In [ ]:
import pandas as pd
import numpy as np

data1 = {'Name':['fathima','nasrin','ke'],'english':[40,60,40],'maths':[40,60,40],'chem':[40,60,40]}
df = pd.DataFrame(data1)

df['social'] = [60,48,50]
df['total marks'] = df['english'] + df['maths'] + df['chem'] + df['social']

list1 = []

for i in df['total marks']:

  if i<=100:
     list1.append('below avrg')
  elif i<=200:
    list1.append('avg')
  else :
    list1.append('excellent')

df['status'] = list1
del df['maths']
df = df.drop('chem',axis = 1) # want to specify axis
df.pop('english')
print(df.columns)
print(df.ndim)
print(df.size)
print(df.shape)


print(df)

Index(['Name', 'social', 'total marks', 'status'], dtype='object')
2
12
(3, 4)
      Name  social  total marks     status
0  fathima      60          180        avg
1   nasrin      48          228  excellent
2       ke      50          170        avg

In [ ]:
import pandas as pd
import numpy as np

data1 = {'Name':['fathima','nasrin','ke'],'english':[40,60,40],'maths':[40,60,40],'chem':[40,60,40]}
df = pd.DataFrame(data1)

df['social'] = [60,48,50]
df['total marks'] = df['english'] + df['maths'] + df['chem'] + df['social']

list1 = []

for i in df['total marks']:

  if i<=100:
     list1.append('below avrg')
  elif i<=200:
    list1.append('avg')
  else :
    list1.append('excellent')

df['status'] = list1
del df['maths']
df = df.drop('chem',axis = 1) # want to specify axis
df.pop('english')
print('\n')
print(df.columns)
print('\n')
print(df.ndim)
print('\n')
print(df.size)
print('\n')
print(df.shape)

print(df['status'].unique())
print(df['social'].unique())
print(df['status'].value_counts())


print(df)

Index(['Name', 'social', 'total marks', 'status'], dtype='object')


2


12


(3, 4)
['avg' 'excellent']
[60 48 50]
status
avg          2
excellent    1
Name: count, dtype: int64
      Name  social  total marks     status
0  fathima      60          180        avg
1   nasrin      48          228  excellent
2       ke      50          170        avg

In [ ]:
print(df.head(2))

      Name  social  total marks     status
0  fathima      60          180        avg
1   nasrin      48          228  excellent

In [ ]:
print(df.tail(2))

     Name  social  total marks     status
1  nasrin      48          228  excellent
2      ke      50          170        avg

In [ ]:
print(df.describe())

          social  total marks
count   3.000000     3.000000
mean   52.666667   192.666667
std     6.429101    31.005376
min    48.000000   170.000000
25%    49.000000   175.000000
50%    50.000000   180.000000
75%    55.000000   204.000000
max    60.000000   228.000000

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         3 non-null      object
 1   social       3 non-null      int64
 2   total marks  3 non-null      int64
 3   status       3 non-null      object
dtypes: int64(2), object(2)
memory usage: 224.0+ bytes
None

In [ ]:
print(df.sum())

Name           fathimanasrinke
social                     158
total marks                578
status         avgexcellentavg
dtype: object

In [ ]:
print(df['social'].sum())

158

In [ ]:
print(df.sum(1))#row wise

TypeError: can only concatenate str (not "int") to str

In [ ]:
print(df.sum(0))#column wise

Name           fathimanasrinke
social                     158
total marks                578
status         avgexcellentavg
dtype: object

In [ ]:
print(df['social'].mean())

52.666666666666664

In [26]:
import pandas as pd
import numpy as np

data1 = [['Ram',40,40,60,40,60,12,4,6,4],['Ebin',60,30,90,40,60,40],['John',40,50,1240,60,40]]

data2 = {'Name':['Ram','Ebin','Sarang','Ram','Ebin','Sarang','Ram','Ebin','Sarang'],'Chem':[40,60,40,40,60,40,40,60,40],'Maths':[40,60,40,40,60,40,40,60,40],'Phy':[40,60,40,40,60,40,40,60,40]}

df = pd.DataFrame(data2)

df['Bio'] = [40,60,40,40,60,40,40,60,40]

df['Total Mark'] = df["Chem"] + df["Maths"] + df["Phy"] + df["Bio"]

print(df)

print('\n')

     Name  Chem  Maths  Phy  Bio  Total Mark
0     Ram    40     40   40   40         160
1    Ebin    60     60   60   60         240
2  Sarang    40     40   40   40         160
3     Ram    40     40   40   40         160
4    Ebin    60     60   60   60         240
5  Sarang    40     40   40   40         160
6     Ram    40     40   40   40         160
7    Ebin    60     60   60   60         240
8  Sarang    40     40   40   40         160

# iloc method

iloc method is used in pandas for indexing.

In [27]:
import pandas as pd
import numpy as np

data1 = [['Ram',40,40,60,40,60,12,4,6,4],['Ebin',60,30,90,40,60,40],['John',40,50,1240,60,40]]

data2 = {'Name':['Ram','Ebin','Sarang','Ram','Ebin','Sarang','Ram','Ebin','Sarang'],'Chem':[40,60,40,40,60,40,40,60,40],'Maths':[40,60,40,40,60,40,40,60,40],'Phy':[40,60,40,40,60,40,40,60,40]}

df = pd.DataFrame(data2)

df['Bio'] = [40,60,40,40,60,40,40,60,40]

df['Total Mark'] = df["Chem"] + df["Maths"] + df["Phy"] + df["Bio"]

print(df)
df1 = df.iloc[0:5,0:4]

print('\n')

     Name  Chem  Maths  Phy  Bio  Total Mark
0     Ram    40     40   40   40         160
1    Ebin    60     60   60   60         240
2  Sarang    40     40   40   40         160
3     Ram    40     40   40   40         160
4    Ebin    60     60   60   60         240
5  Sarang    40     40   40   40         160
6     Ram    40     40   40   40         160
7    Ebin    60     60   60   60         240
8  Sarang    40     40   40   40         160

In [28]:
import pandas as pd
import numpy as np

data1 = [['Ram',40,40,60,40,60,12,4,6,4],['Ebin',60,30,90,40,60,40],['John',40,50,1240,60,40]]

data2 = {'Name':['Ram','Ebin','Sarang','Ram','Ebin','Sarang','Ram','Ebin','Sarang'],'Chem':[40,60,40,40,60,40,40,60,40],'Maths':[40,60,40,40,60,40,40,60,40],'Phy':[40,60,40,40,60,40,40,60,40]}

df = pd.DataFrame(data2)

df['Bio'] = [40,60,40,40,60,40,40,60,40]

df['Total Mark'] = df["Chem"] + df["Maths"] + df["Phy"] + df["Bio"]

print(df)
df2 = df.loc[:4,:'Phy']


print('\n')

     Name  Chem  Maths  Phy  Bio  Total Mark
0     Ram    40     40   40   40         160
1    Ebin    60     60   60   60         240
2  Sarang    40     40   40   40         160
3     Ram    40     40   40   40         160
4    Ebin    60     60   60   60         240
5  Sarang    40     40   40   40         160
6     Ram    40     40   40   40         160
7    Ebin    60     60   60   60         240
8  Sarang    40     40   40   40         160

# at method

In [29]:
import pandas as pd
import numpy as np

data1 = [['Ram',40,40,60,40,60,12,4,6,4],['Ebin',60,30,90,40,60,40],['John',40,50,1240,60,40]]

data2 = {'Name':['Ram','Ebin','Sarang','Ram','Ebin','Sarang','Ram','Ebin','Sarang'],'Chem':[40,60,40,40,60,40,40,60,40],'Maths':[40,60,40,40,60,40,40,60,40],'Phy':[40,60,40,40,60,40,40,60,40]}

df = pd.DataFrame(data2)

df['Bio'] = [40,60,40,40,60,40,40,60,40]

df['Total Mark'] = df["Chem"] + df["Maths"] + df["Phy"] + df["Bio"]

#print(df)

print('\n')

df3 = df.at[0,'Phy']

print(df3)

40

#iat method

In [30]:
import pandas as pd
import numpy as np

data1 = [['Ram',40,40,60,40,60,12,4,6,4],['Ebin',60,30,90,40,60,40],['John',40,50,1240,60,40]]

data2 = {'Name':['Ram','Ebin','Sarang','Ram','Ebin','Sarang','Ram','Ebin','Sarang'],'Chem':[40,60,40,40,60,40,40,60,40],'Maths':[40,60,40,40,60,40,40,60,40],'Phy':[40,60,40,40,60,40,40,60,40]}

df = pd.DataFrame(data2)

df['Bio'] = [40,60,40,40,60,40,40,60,40]

df['Total Mark'] = df["Chem"] + df["Maths"] + df["Phy"] + df["Bio"]

#print(df)

print('\n')

df4 = df.iat[0,3]

print(df4)

40

pipe Method

In [31]:
import pandas as pd
import numpy as np

data01 = [[40,50,70,20,30,10],[20,30,40,50,60,70],[50,60,70,80,90,30]]

df = pd.DataFrame(data01)

def adder(a,b):
  return a+b

print(df)

print('\n')

df1 = df.pipe(adder,2)

print(df1)

    0   1   2   3   4   5
0  40  50  70  20  30  10
1  20  30  40  50  60  70
2  50  60  70  80  90  30


    0   1   2   3   4   5
0  42  52  72  22  32  12
1  22  32  42  52  62  72
2  52  62  72  82  92  32

In [ ]:
import pandas as pd
import numpy as np
data = [[40,60,30,40,50,12,451],[40,60,88,98,12,47],[40,50,60,70,90,88]]
df = pd.DataFrame(data)
def adder(a,b):
  return a+b
print(df)
df1 = df.pipe(adder,3)
print(df1)

    0   1   2   3   4   5      6
0  40  60  30  40  50  12  451.0
1  40  60  88  98  12  47    NaN
2  40  50  60  70  90  88    NaN
    0   1   2    3   4   5      6
0  43  63  33   43  53  15  454.0
1  43  63  91  101  15  50    NaN
2  43  53  63   73  93  91    NaN

AXIS AND APPLY FUNCTION

In [ ]:
import pandas as pd
import numpy as np
data = [[40,60,30,40,50,12,451],[40,60,88,98,12,47],[40,50,60,70,90,88]]
df = pd.DataFrame(data)
def adder(a):
  return a**2
print(df)
df1 = df.apply(adder,axis=0)    # column wise
print(df1)

    0   1   2   3   4   5      6
0  40  60  30  40  50  12  451.0
1  40  60  88  98  12  47    NaN
2  40  50  60  70  90  88    NaN
      0     1     2     3     4     5         6
0  1600  3600   900  1600  2500   144  203401.0
1  1600  3600  7744  9604   144  2209       NaN
2  1600  2500  3600  4900  8100  7744       NaN

In [ ]:
import pandas as pd
import numpy as np
data = [[40,60,30,40,50,12,451],[40,60,88,98,12,47],[40,50,60,70,90,88]]
df = pd.DataFrame(data)
def adder(a):
  return a**2
print(df)
df1 = df.apply(adder,axis=1)   #row wise
print(df1)

    0   1   2   3   4   5      6
0  40  60  30  40  50  12  451.0
1  40  60  88  98  12  47    NaN
2  40  50  60  70  90  88    NaN
        0       1       2       3       4       5         6
0  1600.0  3600.0   900.0  1600.0  2500.0   144.0  203401.0
1  1600.0  3600.0  7744.0  9604.0   144.0  2209.0       NaN
2  1600.0  2500.0  3600.0  4900.0  8100.0  7744.0       NaN

MEAN

In [ ]:
import pandas as pd
import numpy as np
data = [[40,60,30,40,50,12,451],[40,60,88,98,12,47],[40,50,60,70,90,88]]
df = pd.DataFrame(data)
def adder(a):
  return a**2
print(df)
df1 = df.apply(np.mean,axis=0)    # column wise
print(df1)

    0   1   2   3   4   5      6
0  40  60  30  40  50  12  451.0
1  40  60  88  98  12  47    NaN
2  40  50  60  70  90  88    NaN
0     40.000000
1     56.666667
2     59.333333
3     69.333333
4     50.666667
5     49.000000
6    451.000000
dtype: float64

In [ ]:
import pandas as pd
import numpy as np
data = [[40,60,30,40,50,12,451],[40,60,88,98,12,47],[40,50,60,70,90,88]]
df = pd.DataFrame(data)
def adder(a):
  return a**2
print(df)
df1 = df.apply(np.mean,axis=1)   #row wise
print(df1)

    0   1   2   3   4   5      6
0  40  60  30  40  50  12  451.0
1  40  60  88  98  12  47    NaN
2  40  50  60  70  90  88    NaN
0    97.571429
1    57.500000
2    66.333333
dtype: float64

In [ ]:
import pandas as pd
import numpy as np
data = [[40,60,30,40,50,12,451],[40,60,88,98,12,47],[40,50,60,70,90,88]]
df = pd.DataFrame(data)
def adder(a):
  return a+b
print(df)
df1 = df.apply(np.sum)
print(df1)

    0   1   2   3   4   5      6
0  40  60  30  40  50  12  451.0
1  40  60  88  98  12  47    NaN
2  40  50  60  70  90  88    NaN
0    120.0
1    170.0
2    178.0
3    208.0
4    152.0
5    147.0
6    451.0
dtype: float64

In [ ]:
import pandas as pd
import numpy as np
data = [[40,60,30,40,50,12,451],[40,60,88,98,12,47],[40,50,60,70,90,88]]
df = pd.DataFrame(data)
def adder(a):
  return a.sum()
print(df)
df1 = df.apply(adder,axis=0)      #column wise
print(df1)

    0   1   2   3   4   5      6
0  40  60  30  40  50  12  451.0
1  40  60  88  98  12  47    NaN
2  40  50  60  70  90  88    NaN
0    120.0
1    170.0
2    178.0
3    208.0
4    152.0
5    147.0
6    451.0
dtype: float64

In [ ]:
import pandas as pd
import numpy as np
data = [[40,60,30,40,50,12,451],[40,60,88,98,12,47],[40,50,60,70,90,88]]
df = pd.DataFrame(data)
def adder(a):
  return a.sum()

print(df)
df1 = df.apply(adder,axis=1)      #row wise
print(df1)

    0   1   2   3   4   5      6
0  40  60  30  40  50  12  451.0
1  40  60  88  98  12  47    NaN
2  40  50  60  70  90  88    NaN
0    683.0
1    345.0
2    398.0
dtype: float64

In [ ]:
import pandas as pd
import numpy as np
data = [[40,60,30,40,50,12,451],[40,60,88,98,12,47],[40,50,60,70,90,88]]
df = pd.DataFrame(data)
def adder(a):
  return a.sum()

print(df)
df1 = df.apply(lambda x:x.max()-x.min(),axis=0)      #column wise
print(df1)

    0   1   2   3   4   5      6
0  40  60  30  40  50  12  451.0
1  40  60  88  98  12  47    NaN
2  40  50  60  70  90  88    NaN
0     0.0
1    10.0
2    58.0
3    58.0
4    78.0
5    76.0
6     0.0
dtype: float64

In [ ]:
import pandas as pd
import numpy as np
data = [[40,60,30,40,50,12,451],[40,60,88,98,12,47],[40,50,60,70,90,88]]
df = pd.DataFrame(data)
def adder(a):
  return a.sum()

print(df)
df1 = df.apply(lambda x:x.max()-x.min(),axis=1)      #row wise
print(df1)

    0   1   2   3   4   5      6
0  40  60  30  40  50  12  451.0
1  40  60  88  98  12  47    NaN
2  40  50  60  70  90  88    NaN
0    439.0
1     86.0
2     50.0
dtype: float64